<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
/usr/lib/python2.6/cgitb.py:173: DeprecationWarning: BaseException.message has been 
deprecated as of Python 2.6
  value = pydoc.html.repr(getattr(evalue, name))
</table> </table> </table> </table> </table> </font> </font> </font><body 
bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>&lt;type 
'exceptions.AttributeError'&gt;</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 2.6: /usr/bin/python<br>Wed Oct 31 
03:02:57 2012</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a 
href="file:///home/olpc/Activities/Learn.activity/cgi-bin/fetchMilestone.py">/home/olpc/Activities/Learn.activity/cgi-bin/fetchMilestone.py</a> 
in <strong><module></strong>()</td></tr>
<tr><td><font 
color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;33</small>&nbsp;milestone&nbsp;=&nbsp;form.getfirst('milestone')<br>
</tt></font></td></tr>
<tr><td><font 
color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;34</small>&nbsp;subject&nbsp;=&nbsp;form.getfirst('subject')<br>
</tt></font></td></tr>
<tr><td 
bgcolor="#ffccee"><tt><small>&nbsp;&nbsp;&nbsp;35</small>&nbsp;course&nbsp;=&nbsp;form.getfirst('course').replace('\n','')<br>
</tt></td></tr>
<tr><td><font 
color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;36</small>&nbsp;course_type&nbsp;=&nbsp;form.getfirst('course_type')<br>
</tt></font></td></tr>
<tr><td><font 
color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;37</small>&nbsp;enrollment&nbsp;=&nbsp;form.getfirst('enrollment')<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090">course <em>undefined</em>, 
<strong>form</strong>&nbsp;= FieldStorage(None, None, []), 
form.<strong>getfirst</strong>&nbsp;= &lt;bound method FieldStorage.getfirst of 
FieldStorage(None, None, [])&gt;, ).replace 
<em>undefined</em></font></small></td></tr></table><p><strong>&lt;type 
'exceptions.AttributeError'&gt;</strong>: 'NoneType' object has no attribute 'replace'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
("'NoneType' object has no attribute 'replace'",)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>message&nbsp;=
"'NoneType' object has no attribute 'replace'"


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "fetchMilestone.py", line 35, in &lt;module&gt;
    course = form.getfirst('course').replace('\n','')
AttributeError: 'NoneType' object has no attribute 'replace'

-->

